### ISSUE TITLE
Delete the mob spawners

### ISSUE THREAD

**Issue by n08i40k** [banimania/AnarchyCore#1]
Some servers have premium stores (purchase for real money) and you can buy a spawner there, but the plugin will delete them. Please remove this.

https://github.com/banimania/AnarchyCore/blob/5fcc9a76150a1073e333509c151640f25db4ccd5/src/main/java/com/danimania/anarchycore/utils/IllegalUtils.java#L40

**Comment by danimania-dev** [comment]
Hi, thanks you for reaching this to us. The anti-illegal has not been implemented yet. When we implement it we will also add a configuration file so you can manage what illegals do you want to remove.

**Comment by danimania-dev** [comment]
Will close this issue, if you still need more help reach us at our Discord ([https://discord.gg/nVXAWYJ256]) or open a new issue.
