### ISSUE TITLE
AnarchyCore enabling default death messages

### ISSUE THREAD

**Issue by tomiiiiiiiii** [banimania/AnarchyCore#2]
Hi, for some reason, when I add AnarchyCore to my server, it enables the default death messages, even after disabling the death messages thing.

By the way, I'm using DeathMessages for the custom death messages. 
Please fix.

**Comment by danimania-dev** [comment]
Can you send your config.yml file?

**Comment by tomiiiiiiiii** [comment]
https://pastebin.com/dcVq9f0B
That's my config.

**Comment by danimania-dev** [comment]
Should be fixed in the last release. Please check it out.

**Comment by tomiiiiiiiii** [comment]
Thanks! Now the default death messages don't appear.
